<a href="https://colab.research.google.com/github/PrzemekTeska/175IC-machine-learning/blob/main/zad_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

data = {
    'size': ['L', 'M', 'XL', 'S', 'XS', 'S', 'S', 'M', 'L', 'XXL', 'L', 'M', 'M', 'XS', 'S', 'XL', 'L', 'S', 'M'],
    'color': ['green', 'red', 'blue', 'black', 'white', 'yellow', 'purple', 'cyan', 'black', 'black', 'white', 'blue', 'red', 'green', 'blue', 'white', 'white', 'black', 'white'],
    'gender': ['female', 'female', 'male', 'female', 'female', 'male', 'female', 'male', 'female', 'male', 'male', 'female', 'male', 'female', 'male', 'female', 'male', 'male', 'female'],
    'price': [90.0, 15.0, 35.0, 60.0, 80.0, 45.0, 70.0, 150.0, 180.0, 30.0, 20.0, 40.0, 50.0, 60.0, 20.0, 10.0, 40.0, 150.0, 180.0],
    'weight': [20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380],
    'bought': ['yes', 'yes', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes', 'no']
}

df_raw = pd.DataFrame(data=data)

df = df_raw.copy()

for col in ['size', 'color', 'gender', 'bought']:
    df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float64')    

df.info()

df.describe(include='category').T

le = LabelEncoder()
df['bought'] = le.fit_transform(df['bought'])

df = pd.get_dummies(data=df, drop_first=True)

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    19 non-null     category
 1   color   19 non-null     category
 2   gender  19 non-null     category
 3   price   19 non-null     float64
 4   weight  19 non-null     float64
 5   bought  19 non-null     category
dtypes: category(4), float64(2)
memory usage: 1.3 KB

       price    weight  bought  ...  color_white  color_yellow  gender_male
0   0.376709 -1.643168       1  ...            0             0            0
1  -1.017605 -1.460593       1  ...            0             0            0
2  -0.645788 -1.278019       1  ...            0             0            1
3  -0.181016 -1.095445       0  ...            0             0            0
4   0.190801 -0.912871       0  ...            1             0            0
5  -0.459879 -0.730297       1  ...            0             1            1
6   0.004892 -0.547723       0  ...            0             0            0
7   1.492161 -0.365148       1  ...            0             0            1
8   2.049886 -0.182574       1  ...            0             0            0
9  -0.738742  0.000000       0  ...            0             0            1
10 -0.924650  0.182574       0  ...            1             0            1
11 -0.552833  0.365148       0  ...            0             0            0
12 -0.366925  0.547723       0  ...            0             0            1
13 -0.181016  0.730297       1  ...            0             0            0
14 -0.924650  0.912871       1  ...            0             0            1
15 -1.110559  1.095445       0  ...            1             0            0
16 -0.552833  1.278019       0  ...            1             0            1
17  1.492161  1.460593       1  ...            0             0            1
18  2.049886  1.643168       0  ...            1             0            0

[19 rows x 16 columns]